#!/bin/bash
set -ueo pipefail

if [[ -n "${DEBUG:-}" ]]; then
    set -x
fi

if [[ ! -d /sys/kernel/config/usb_gadget ]]; then
    echo "ERROR: ConfigFS not found. is libcomposite loaded?"
    exit 1
fi

cd /sys/kernel/config/usb_gadget
[[ -d usb-network ]] || mkdir usb-network
cd usb-network

echo "0x1d6b" > idVendor
echo "0x0104" > idProduct

[[ -d strings/0x409 ]] || mkdir strings/0x409
(
    cd strings/0x409
    echo "Arch Linux" > manufacturer
    echo "Arch Linux USB network" > product
)

[[ -d functions/ncm.usb0 ]] || mkdir functions/ncm.usb0

[[ -d configs/c.1 ]] || mkdir configs/c.1
[[ -d configs/c.1/strings/0x409 ]] || mkdir configs/c.1/strings/0x409

echo "USB network" > configs/c.1/strings/0x409/configuration

[[ -e configs/c.1/ncm.usb0 ]] || ln -s "$(pwd)/functions/ncm.usb0" configs/c.1/

[[ -n "$(cat UDC)" ]] || echo "$(ls -1 /sys/class/udc | head -n1)" > UDC

ip link set usb0 up
ip addr replace 172.16.42.1/24 dev usb0
