
name: PKGBUILDs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd PKGBUILDs/linux-msm8916-pmos
          CARCH=aarch64 EUID=123 makepkg -si
      - uses: actions/upload-artifact@v4
        with:
          name: linux-msm8916-pmos
          path: PKGBUILDs/**/*.pkg.tar.zst
