
name: PKGBUILDs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  aur:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - dracut-sshd-git
          - unudhcpd
    steps:
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: archarm_latest
          run: |
            set -uexo pipefail

            pacman="pacman --noconfirm --noprogressbar"

            $pacman -Syu git
            git clone https://aur.archlinux.org/${{matrix.package}}.git
            srcinfo="${{matrix.package}}/.SRCINFO"
            pkgver=$(cat "${srcinfo}" | grep "pkgver =" | cut -d'=' -f2 | xargs)
            pkgrel=$(cat "${srcinfo}" | grep "pkgrel =" | cut -d'=' -f2 | xargs)
            pkgname=$(cat "${srcinfo}" | grep "pkgname =" | head -n1 | cut -d'=' -f2 | xargs)
            pkgarch=$(cat "${srcinfo}" | grep "arch =" | head -n1 | cut -d'=' -f2 | xargs)

            pkg="${pkgname}-${pkgver}-${pkgrel}-${pkgarch}"
            if curl -I --fail -s "https://archlinux-msm8916.samcday.com/${pkg}.pkg.tar.zst"; then
              echo "${pkg} already exists, skipping build"
              exit
            fi

            $pacman -S base-devel sudo

            useradd builder -m
            echo 'builder ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers

            BUILDDIR=${GITHUB_WORKSPACE}/_build
            PKGDEST=${GITHUB_WORKSPACE}/_pkg
            SRCDEST=${GITHUB_WORKSPACE}/_src

            mkdir $BUILDDIR $PKGDEST $SRCDEST
            chown builder:builder $BUILDDIR $PKGDEST $SRCDEST

            cd ${{matrix.package}}
            sudo -u builder \
              BUILDDIR="$BUILDDIR" \
              PKGDEST="$PKGDEST" \
              SRCDEST="$SRCDEST" \
              makepkg --noconfirm -s
      - uses: actions/upload-artifact@v4
        with:
          name: package-${{matrix.package}}
          path: _pkg/**/*.pkg.tar.zst
  linux-msm8916-pmos:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v4
      - name: build package
        run: |
          set -uexo pipefail

          srcinfo="PKGBUILDs/linux-msm8916-pmos/.SRCINFO"
          pkgver=$(cat "${srcinfo}" | grep "pkgver =" | cut -d'=' -f2 | xargs)
          pkgrel=$(cat "${srcinfo}" | grep "pkgrel =" | cut -d'=' -f2 | xargs)
          pkgname=$(cat "${srcinfo}" | grep "pkgname =" | head -n1 | cut -d'=' -f2 | xargs)
          pkgarch=$(cat "${srcinfo}" | grep "arch =" | head -n1 | cut -d'=' -f2 | xargs)

          pkg="${pkgname}-${pkgver}-${pkgrel}-${pkgarch}"
          if curl -I --fail -s "https://archlinux-msm8916.samcday.com/${pkg}.pkg.tar.zst"; then
            echo "${pkg} already exists, skipping build"
            exit
          fi

          pacman="pacman --noconfirm --noprogressbar"
          $pacman -Sy sudo
          useradd builder -m
          echo 'builder ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers

          BUILDDIR=${GITHUB_WORKSPACE}/_build
          PKGDEST=${GITHUB_WORKSPACE}/_pkg
          SRCDEST=${GITHUB_WORKSPACE}/_src

          mkdir $BUILDDIR $PKGDEST $SRCDEST
          chown builder:builder $BUILDDIR $PKGDEST $SRCDEST

          cd PKGBUILDs/linux-msm8916-pmos
          sudo -u builder \
            BUILDDIR="$BUILDDIR" \
            PKGDEST="$PKGDEST" \
            SRCDEST="$SRCDEST" \
            CARCH=aarch64 \
            makepkg --noconfirm -s
      - uses: actions/upload-artifact@v4
        with:
          name: package-linux-msm8916-pmos
          path: _pkg/**/*.pkg.tar.zst
  repo_upload:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    needs:
      - aur
      - linux-msm8916-pmos
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: repo/
          pattern: package-*
          merge-multiple: true
      - name: publish new packages
        env:
          RCLONE_CONFIG_BUCKET_TYPE: b2
          RCLONE_CONFIG_BUCKET_ACCOUNT: ${{secrets.BUCKET_ACCOUNT}}
          RCLONE_CONFIG_BUCKET_KEY: ${{secrets.BUCKET_KEY}}
        run: |
          set -uexo pipefail

          if [[ -z "$(find repo/ -name '*.pkg.tar.zst')" ]]; then
            echo "no new packages to publish"
            exit
          fi

          pacman -Sy --noconfirm rclone
          bucket=samcday-archlinux-msm8916

          rclone copy BUCKET:$bucket/msm8916.db repo/
          rclone copy BUCKET:$bucket/msm8916.files repo/

          ln -s msm8916.db repo/msm8916.db.tar.xz
          ln -s msm8916.files repo/msm8916.files.tar.xz

          repo-add repo/msm8916.db.tar.xz repo/*.pkg.tar.zst

          rclone copy --include '*.pkg.tar.zst' repo/ BUCKET:$bucket/
          rclone copy -L repo/msm8916.db BUCKET:$bucket/
          rclone copy -L repo/msm8916.files BUCKET:$bucket/
