
name: PKGBUILDs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v3
      - run: |
          pacman="pacman --noconfirm --noprogressbar"
          $pacman -Sy sudo
          useradd builder -m
          echo 'builder ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers

          export BUILDDIR=${GITHUB_WORKSPACE}/_build
          export PKGDEST=${GITHUB_WORKSPACE}/_pkg
          export SRCDEST=${GITHUB_WORKSPACE}/_src

          mkdir $BUILDDIR $PKGDEST $SRCDEST
          chown builder:builder $BUILDDIR $PKGDEST $SRCDEST

          cd PKGBUILDs/linux-msm8916-pmos
          sudo -u builder CARCH=aarch64 makepkg --noconfirm -s
          CARCH=aarch64 makepkg -si
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: _pkg/**/*.pkg.tar.zst
